### ISSUE TITLE
Episode 13 question

### ISSUE THREAD

**Issue by anselal** [alphascriptyt/Discord_Rewrite_Tutorials#4]
at **https://github.com/alphascriptyt/Discord_Rewrite_Tutorials/blob/master/episodes/episode-13.py**
The pages do not change when I add a reaction. I gave my bot permissions to read channel history. What other permissions does the bot need for the custom help to work properly ?

**Comment by alphascriptyt** [comment]
Hi, you would need the 'Manage Messages', 'Send Messages', 'Add Reactions' permissions I believe.

**Comment by anselal** [comment]
Will try manage messages, although it seems too much, cause it only changes its own message, but I will try it. give me a sec

**Comment by anselal** [comment]
@alphascriptyt it worked !!! thnx mate. Is it supposed to be so slow ? it takes a second or two to display the next Embed

**Comment by alphascriptyt** [comment]
Awesome, I'm glad. It shouldn't, that is probably due to the removing of reactions. Is it as slow as it is in the video?

**Comment by anselal** [comment]
yes, it is as slow as in the video
