### ISSUE TITLE
To add Pause and Resume Command

### ISSUE THREAD

**Issue by nisarg0606** [alphascriptyt/Discord_Rewrite_Tutorials#8]
`@commands.command()
    async def pause(self, ctx):
        if ctx.voice_client is None:
            return await ctx.send("I am not connected to a voice channel.")

        if ctx.voice_client.is_paused():
            return await ctx.send("I am already paused.")

        ctx.voice_client.pause()
        await ctx.send("Paused.⏸️")
    
    @commands.command()
    async def resume(self, ctx):
        if ctx.voice_client is None:
            return await ctx.send("I am not connected to a voice channel.")

        if not ctx.voice_client.is_paused():
            return await ctx.send("I am not paused.")
        
        ctx.voice_client.resume()
        await ctx.send("Resumed.▶️")`

**Comment by nisarg0606** [comment]
I think in today's world each and every bot do need yo use resume and pause command... so, I am contributing to add pause and resume command

**Comment by alphascriptyt** [comment]
Hi, thank you! I will add this now. 
Sorry for my late reply, I have been away.
