### ISSUE TITLE
Problem With The Bot Constantly Stopping The Music Midway

### ISSUE THREAD

**Issue by TOG6-6** [alphascriptyt/Discord_Rewrite_Tutorials#9]
Hey, for starters I just wanted to let you know, the code was really really helpful, especially for someone, who's just starting.

I also managed to make numerous changes (not ones that make it better, ones that make it more customized for my bot) thanks to your easy to understand code.

However I've been facing this problem where any music I play ends up stopping half way, and I can't figure out why. I would greatly appreciate it if you could help me out.

My error:
Startup [tls @ 0x55c532372880] Error in the pull function.
Startup [matroska,webm @ 0x55c53236fa40] Read error
Startup [tls @ 0x55c532372880] The specified session has been invalidated for some reason.
Startup Last message repeated 1 times

Again, even if you don't reply, but read this, thanks a lot for your time and effort in uploading this code! :)

**Comment by acidOP** [comment]
Hey have you figured out any solution? Let me know. Thanks
